image: maven:3.9.8-eclipse-temurin-22-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - health-check
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

health-check:
  stage: health-check
  image: curlimages/curl
  script:
    - curl $ACTUATOR_HEALTH_URL | grep "{\"status\":\"UP\"}" || ( echo Health Check Failed Actuator=$ACTUATOR_HEALTH_URL && exit 2; )

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
  only:
    - main