services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: compose_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gitlab-local
    ports:
      - 5432:5432
    restart: on-failure

  app:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gitlab-local
      - SPRING_DATASOURCE_USERNAME=compose_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    restart: on-failure